/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DataMonthly: typeof import('./components/DataMonthly.vue')['default']
    DataWeekly: typeof import('./components/DataWeekly.vue')['default']
    DataXArea: typeof import('./components/DataXArea.vue')['default']
    DataXLineX: typeof import('./components/DataXLineX.vue')['default']
    DataXTabled: typeof import('./components/DataXTabled.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
