/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./components/DataMaximum copy.vue')['default']
    DataBalance: typeof import('./components/DataBalance.vue')['default']
    DataDaily: typeof import('./components/DataDaily.vue')['default']
    DataMaximum: typeof import('./components/DataMaximum.vue')['default']
    DataMonthly: typeof import('./components/DataMonthly.vue')['default']
    DataWeekly: typeof import('./components/DataWeekly.vue')['default']
    DataWhole: typeof import('./components/DataWhole.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
