/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./components/DataXArea copy.vue')['default']
    DataDaily: typeof import('./components/DataDaily.vue')['default']
    DataMonthly: typeof import('./components/DataMonthly.vue')['default']
    DataWeekly: typeof import('./components/DataWeekly.vue')['default']
    DataXArea: typeof import('./components/DataXArea.vue')['default']
    DataXArea2: typeof import('./components/DataXArea2.vue')['default']
    DataXLineX: typeof import('./components/DataXLineX.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
